version: '3.8'

services:

  wzzzz-celery-worker:
    image: wzzzz-celery-worker
    container_name: wzzzz-celery-worker
    build:
      context: ./api
      dockerfile: celeryworker.dockerfile

  wzzzz-flower:
    image: mher/flower
    container_name: wzzzz-flower
    environment:
      - FLOWER_PORT=5555
    ports:
      - "5556:5555"
    depends_on:
      - wzzzz-celery-worker

  wzzzz-api:
    image: wzzzz-api
    container_name: wzzzz-api
    expose:
      - "8000"
    build:
      context: ./api
      dockerfile: api.dockerfile
    volumes:
      - ./api/app:/app

  wzzzz-bot:
    image: wzzzz-bot
    container_name: wzzzz-bot
    ports:
      - "8002:8000"
    build:
      context: ./bot
      dockerfile: bot.dockerfile
    depends_on:
      - wzzzz-api
    volumes:
      - ./bot/app:/app
