version: '3.8'

services:

  wzzzz-redis-dev:
    image: bitnami/redis:latest
    container_name: wzzzz-redis-dev
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - wzzzz-redis-dev-data:/bitnami/redis/data
    networks:
      - wzzzz-dev-bot-network
      - wzzzz-dev-api-network

  wzzzz-mongo-dev:
    image: mongo:6
    container_name: wzzzz-mongo-dev
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEV_ROOT_USERNAME?Variable not set}
      MONGO_INITDB_ROOT_PASSWORD: ${DEV_ROOT_PASSWORD?Variable not set}
      MONGO_INITDB_DATABASE: dev-db
    volumes:
      - wzzzz-mongo-dev-data:/data/db
    networks:
      - wzzzz-dev-api-network

  wzzzz-mongo-express-dev:
    image: mongo-express
    container_name: wzzzz-mongo-express
    restart: unless-stopped
    env_file: .env
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMINUSERNAME?Variable not set}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMINPASSWORD?Variable not set}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL?Variable not set}
    depends_on:
      - wzzzz-mongo-dev
    networks:
      - wzzzz-dev-api-network

  wzzzz-mongo-test:
    image: mongo
    container_name: wzzzz-mongo-test
    restart: always
    command: mongod --port 27021
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TEST_ROOT_USERNAME?Variable not set}
      MONGO_INITDB_ROOT_PASSWORD: ${TEST_ROOT_PASSWORD?Variable not set}
      MONGO_INITDB_DATABASE: test-db
    networks:
      - wzzzz-dev-api-network

  wzzzz-api:
    ports:
      - "8001:8000"
    env_file: .env
    build:
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    depends_on:
      - wzzzz-mongo-dev
      - wzzzz-mongo-test
    networks:
      - wzzzz-dev-api-network
      - wzzzz-dev-bot-network

  wzzzz-bot:
    env_file: .env
    build:
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    entrypoint: ["watchmedo", "auto-restart", "-d", "app/", "-p", "*.py", "-R", "--", "python", "app/main.py"]
    depends_on:
      - wzzzz-redis-dev
    networks:
      - wzzzz-dev-bot-network

volumes:
  wzzzz-mongo-dev-data:
    driver: local
  wzzzz-redis-dev-data:
    driver: local

networks:
  wzzzz-dev-api-network:
  wzzzz-dev-bot-network:
