version: '3.8'

services:

  wzzzz-redis-prod:
    image: bitnami/redis:latest
    container_name: wzzzz-redis-prod
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - wzzzz-redis-prod-data:/bitnami/redis/data
    networks:
      - wzzzz-prod-bot-network
      - wzzzz-prod-api-network

  wzzzz-celery-worker:
    depends_on:
      - wzzzz-redis-prod
    networks:
      - wzzzz-prod-api-network

  wzzzz-flower:
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL_PROD}
      - FLOWER_BASIC_AUTH=${FLOWER_USERNAME_PROD}:${FLOWER_PASSWORD_PROD}
    depends_on:
      - wzzzz-redis-prod
    networks:
      - wzzzz-prod-api-network

  wzzzz-api:
    networks:
      - wzzzz-prod-api-network
      - wzzzz-prod-bot-network

  wzzzz-bot:
    depends_on:
      - wzzzz-redis-prod
    networks:
      - wzzzz-prod-bot-network

volumes:
  wzzzz-redis-prod-data:
    driver: local

networks:
  wzzzz-prod-api-network:
  wzzzz-prod-bot-network: